"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DropTableSettings = exports.DescribeTableSettings = exports.BeginTransactionSettings = exports.CommitTransactionSettings = exports.RollbackTransactionSettings = exports.PrepareQuerySettings = exports.ExecuteQuerySettings = exports.BulkUpsertSettings = exports.ReadTableSettings = exports.ExecuteScanQuerySettings = exports.Session = exports.TableSession = exports.Column = exports.StorageSettings = exports.ColumnFamilyPolicy = exports.StoragePolicy = exports.ExplicitPartitions = exports.PartitioningPolicy = exports.ReplicationPolicy = exports.CompactionPolicy = exports.ExecutionPolicy = exports.CachingPolicy = exports.TableProfile = exports.TableIndex = exports.TableDescription = exports.AlterTableDescription = exports.TableSessionPool = exports.StatusCode = exports.YdbError = exports.RetryParameters = exports.withRetries = exports.getSACredentialsFromJson = exports.getCredentialsFromEnv = exports.getNameConverter = exports.typeMetadataKey = exports.primitiveTypeToValue = exports.identityConversion = exports.snakeToCamelCaseConversion = exports.withTypeOptions = exports.TypedData = exports.TypedValues = exports.Types = exports.declareType = exports.Driver = exports.getFallbackLogFunction = exports.FallbackLogger = exports.setDefaultLogger = exports.setupLogger = exports.getLogger = exports.Ydb = void 0;
exports.ResultSet = exports.QueryClient = exports.parseConnectionString = exports.MakeDirectorySettings = exports.RemoveDirectorySettings = exports.ListDirectorySettings = exports.DescribePathSettings = exports.ModifyPermissionsSettings = exports.AnonymousAuthService = exports.TokenAuthService = exports.MetadataAuthService = exports.IamAuthService = exports.StaticCredentialsAuthService = exports.AUTO_TX = exports.OperationParams = exports.CreateTableSettings = exports.AlterTableSettings = void 0;
var ydb_sdk_proto_1 = require("ydb-sdk-proto");
Object.defineProperty(exports, "Ydb", { enumerable: true, get: function () { return ydb_sdk_proto_1.Ydb; } });
var deprecated_1 = require("./logger/deprecated");
Object.defineProperty(exports, "getLogger", { enumerable: true, get: function () { return deprecated_1.getLogger; } });
Object.defineProperty(exports, "setupLogger", { enumerable: true, get: function () { return deprecated_1.setupLogger; } });
Object.defineProperty(exports, "setDefaultLogger", { enumerable: true, get: function () { return deprecated_1.setDefaultLogger; } });
Object.defineProperty(exports, "FallbackLogger", { enumerable: true, get: function () { return deprecated_1.FallbackLogger; } });
Object.defineProperty(exports, "getFallbackLogFunction", { enumerable: true, get: function () { return deprecated_1.getFallbackLogFunction; } });
var driver_1 = require("./driver");
Object.defineProperty(exports, "Driver", { enumerable: true, get: function () { return driver_1.default; } });
var types_1 = require("./types");
Object.defineProperty(exports, "declareType", { enumerable: true, get: function () { return types_1.declareType; } });
Object.defineProperty(exports, "Types", { enumerable: true, get: function () { return types_1.Types; } });
Object.defineProperty(exports, "TypedValues", { enumerable: true, get: function () { return types_1.TypedValues; } });
Object.defineProperty(exports, "TypedData", { enumerable: true, get: function () { return types_1.TypedData; } });
Object.defineProperty(exports, "withTypeOptions", { enumerable: true, get: function () { return types_1.withTypeOptions; } });
Object.defineProperty(exports, "snakeToCamelCaseConversion", { enumerable: true, get: function () { return types_1.snakeToCamelCaseConversion; } });
Object.defineProperty(exports, "identityConversion", { enumerable: true, get: function () { return types_1.identityConversion; } });
Object.defineProperty(exports, "primitiveTypeToValue", { enumerable: true, get: function () { return types_1.primitiveTypeToValue; } });
Object.defineProperty(exports, "typeMetadataKey", { enumerable: true, get: function () { return types_1.typeMetadataKey; } });
Object.defineProperty(exports, "getNameConverter", { enumerable: true, get: function () { return types_1.getNameConverter; } });
var parse_env_vars_1 = require("./utils/parse-env-vars");
Object.defineProperty(exports, "getCredentialsFromEnv", { enumerable: true, get: function () { return parse_env_vars_1.getCredentialsFromEnv; } });
Object.defineProperty(exports, "getSACredentialsFromJson", { enumerable: true, get: function () { return parse_env_vars_1.getSACredentialsFromJson; } });
var retries_obsoleted_1 = require("./retries_obsoleted");
Object.defineProperty(exports, "withRetries", { enumerable: true, get: function () { return retries_obsoleted_1.withRetries; } });
Object.defineProperty(exports, "RetryParameters", { enumerable: true, get: function () { return retries_obsoleted_1.RetryParameters; } });
var errors_1 = require("./errors");
Object.defineProperty(exports, "YdbError", { enumerable: true, get: function () { return errors_1.YdbError; } });
Object.defineProperty(exports, "StatusCode", { enumerable: true, get: function () { return errors_1.StatusCode; } });
var table_session_pool_1 = require("./table/table-session-pool");
Object.defineProperty(exports, "TableSessionPool", { enumerable: true, get: function () { return table_session_pool_1.TableSessionPool; } });
var table_session_1 = require("./table/table-session");
Object.defineProperty(exports, "AlterTableDescription", { enumerable: true, get: function () { return table_session_1.AlterTableDescription; } });
var table_session_2 = require("./table/table-session");
Object.defineProperty(exports, "TableDescription", { enumerable: true, get: function () { return table_session_2.TableDescription; } });
var table_session_3 = require("./table/table-session");
Object.defineProperty(exports, "TableIndex", { enumerable: true, get: function () { return table_session_3.TableIndex; } });
var table_session_4 = require("./table/table-session");
Object.defineProperty(exports, "TableProfile", { enumerable: true, get: function () { return table_session_4.TableProfile; } });
var table_session_5 = require("./table/table-session");
Object.defineProperty(exports, "CachingPolicy", { enumerable: true, get: function () { return table_session_5.CachingPolicy; } });
var table_session_6 = require("./table/table-session");
Object.defineProperty(exports, "ExecutionPolicy", { enumerable: true, get: function () { return table_session_6.ExecutionPolicy; } });
var table_session_7 = require("./table/table-session");
Object.defineProperty(exports, "CompactionPolicy", { enumerable: true, get: function () { return table_session_7.CompactionPolicy; } });
var table_session_8 = require("./table/table-session");
Object.defineProperty(exports, "ReplicationPolicy", { enumerable: true, get: function () { return table_session_8.ReplicationPolicy; } });
var table_session_9 = require("./table/table-session");
Object.defineProperty(exports, "PartitioningPolicy", { enumerable: true, get: function () { return table_session_9.PartitioningPolicy; } });
var table_session_10 = require("./table/table-session");
Object.defineProperty(exports, "ExplicitPartitions", { enumerable: true, get: function () { return table_session_10.ExplicitPartitions; } });
var table_session_11 = require("./table/table-session");
Object.defineProperty(exports, "StoragePolicy", { enumerable: true, get: function () { return table_session_11.StoragePolicy; } });
var table_session_12 = require("./table/table-session");
Object.defineProperty(exports, "ColumnFamilyPolicy", { enumerable: true, get: function () { return table_session_12.ColumnFamilyPolicy; } });
var table_session_13 = require("./table/table-session");
Object.defineProperty(exports, "StorageSettings", { enumerable: true, get: function () { return table_session_13.StorageSettings; } });
var table_session_14 = require("./table/table-session");
Object.defineProperty(exports, "Column", { enumerable: true, get: function () { return table_session_14.Column; } });
var table_session_15 = require("./table/table-session");
Object.defineProperty(exports, "TableSession", { enumerable: true, get: function () { return table_session_15.TableSession; } });
Object.defineProperty(exports, "Session", { enumerable: true, get: function () { return table_session_15.TableSession; } });
var table_session_16 = require("./table/table-session");
Object.defineProperty(exports, "ExecuteScanQuerySettings", { enumerable: true, get: function () { return table_session_16.ExecuteScanQuerySettings; } });
var table_session_17 = require("./table/table-session");
Object.defineProperty(exports, "ReadTableSettings", { enumerable: true, get: function () { return table_session_17.ReadTableSettings; } });
var table_session_18 = require("./table/table-session");
Object.defineProperty(exports, "BulkUpsertSettings", { enumerable: true, get: function () { return table_session_18.BulkUpsertSettings; } });
var table_session_19 = require("./table/table-session");
Object.defineProperty(exports, "ExecuteQuerySettings", { enumerable: true, get: function () { return table_session_19.ExecuteQuerySettings; } });
var table_session_20 = require("./table/table-session");
Object.defineProperty(exports, "PrepareQuerySettings", { enumerable: true, get: function () { return table_session_20.PrepareQuerySettings; } });
var table_session_21 = require("./table/table-session");
Object.defineProperty(exports, "RollbackTransactionSettings", { enumerable: true, get: function () { return table_session_21.RollbackTransactionSettings; } });
var table_session_22 = require("./table/table-session");
Object.defineProperty(exports, "CommitTransactionSettings", { enumerable: true, get: function () { return table_session_22.CommitTransactionSettings; } });
var table_session_23 = require("./table/table-session");
Object.defineProperty(exports, "BeginTransactionSettings", { enumerable: true, get: function () { return table_session_23.BeginTransactionSettings; } });
var table_session_24 = require("./table/table-session");
Object.defineProperty(exports, "DescribeTableSettings", { enumerable: true, get: function () { return table_session_24.DescribeTableSettings; } });
var table_session_25 = require("./table/table-session");
Object.defineProperty(exports, "DropTableSettings", { enumerable: true, get: function () { return table_session_25.DropTableSettings; } });
var table_session_26 = require("./table/table-session");
Object.defineProperty(exports, "AlterTableSettings", { enumerable: true, get: function () { return table_session_26.AlterTableSettings; } });
var table_session_27 = require("./table/table-session");
Object.defineProperty(exports, "CreateTableSettings", { enumerable: true, get: function () { return table_session_27.CreateTableSettings; } });
var table_session_28 = require("./table/table-session");
Object.defineProperty(exports, "OperationParams", { enumerable: true, get: function () { return table_session_28.OperationParams; } });
var table_session_29 = require("./table/table-session");
Object.defineProperty(exports, "AUTO_TX", { enumerable: true, get: function () { return table_session_29.AUTO_TX; } });
var static_credentials_auth_service_1 = require("./credentials/static-credentials-auth-service");
Object.defineProperty(exports, "StaticCredentialsAuthService", { enumerable: true, get: function () { return static_credentials_auth_service_1.StaticCredentialsAuthService; } });
var iam_auth_service_1 = require("./credentials/iam-auth-service");
Object.defineProperty(exports, "IamAuthService", { enumerable: true, get: function () { return iam_auth_service_1.IamAuthService; } });
var metadata_auth_service_1 = require("./credentials/metadata-auth-service");
Object.defineProperty(exports, "MetadataAuthService", { enumerable: true, get: function () { return metadata_auth_service_1.MetadataAuthService; } });
var token_auth_service_1 = require("./credentials/token-auth-service");
Object.defineProperty(exports, "TokenAuthService", { enumerable: true, get: function () { return token_auth_service_1.TokenAuthService; } });
var anonymous_auth_service_1 = require("./credentials/anonymous-auth-service");
Object.defineProperty(exports, "AnonymousAuthService", { enumerable: true, get: function () { return anonymous_auth_service_1.AnonymousAuthService; } });
var scheme_service_1 = require("./schema/scheme-service");
Object.defineProperty(exports, "ModifyPermissionsSettings", { enumerable: true, get: function () { return scheme_service_1.ModifyPermissionsSettings; } });
var scheme_service_2 = require("./schema/scheme-service");
Object.defineProperty(exports, "DescribePathSettings", { enumerable: true, get: function () { return scheme_service_2.DescribePathSettings; } });
var scheme_service_3 = require("./schema/scheme-service");
Object.defineProperty(exports, "ListDirectorySettings", { enumerable: true, get: function () { return scheme_service_3.ListDirectorySettings; } });
var scheme_service_4 = require("./schema/scheme-service");
Object.defineProperty(exports, "RemoveDirectorySettings", { enumerable: true, get: function () { return scheme_service_4.RemoveDirectorySettings; } });
var scheme_service_5 = require("./schema/scheme-service");
Object.defineProperty(exports, "MakeDirectorySettings", { enumerable: true, get: function () { return scheme_service_5.MakeDirectorySettings; } });
var parse_connection_string_1 = require("./utils/parse-connection-string");
Object.defineProperty(exports, "parseConnectionString", { enumerable: true, get: function () { return parse_connection_string_1.parseConnectionString; } });
var query_1 = require("./query");
Object.defineProperty(exports, "QueryClient", { enumerable: true, get: function () { return query_1.QueryClient; } });
Object.defineProperty(exports, "ResultSet", { enumerable: true, get: function () { return query_1.ResultSet; } });
